name: Docs

on:
  push:
    branches:
      - master

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build pyamrex
        run: docker build -t pyamrex .
      - name: Build docs
        run: docker run -v ${GITHUB_WORKSPACE}/docs:/workspace pyamrex make html
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/build/html
